version: '2'
services:
    health-app:
        image: health
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://health-mysql:3306/health?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=health-elasticsearch:9300
        ports:
            - 8080:8080
    health-mysql:
        extends:
            file: mysql.yml
            service: health-mysql
    health-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: health-elasticsearch
